# cloudbuild.yaml
# CI/CD for data ingestion Cloud Function + Pub/Sub + BigQuery wiring.

substitutions:
  # Keep the pinned SDK version for stability
  _SDK_TAG: '489.0.0-stable'
  _GCP_REGION: 'us-central1'
  _TRIGGER_TOPIC: 'run-daily-ingestion'
  _PUB_SUB_TOPIC: 'daily-bars-raw'
  # IMPORTANT: This project number is critical for the fix.
  _GCP_PROJECT_NUMBER: '81308911755'
  _BIGQUERY_DATASET: 'quant_data'
  _BIGQUERY_TABLE: 'daily_bars_raw'
  _BIGQUERY_SUB_ID: 'daily-bars-raw-bq-sub'
  # The service account that the Cloud Function will run as.
  _FUNCTION_SERVICE_ACCOUNT: 'mjblank2@quant-setup.iam.gserviceaccount.com'
  # The service account that runs the build process.
  _BUILD_SERVICE_ACCOUNT: '${_GCP_PROJECT_NUMBER}@cloudbuild.gserviceaccount.com'


steps:
# STEP 0: Enable required APIs (idempotent).
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:${_SDK_TAG}'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud services enable \
        cloudfunctions.googleapis.com \
        eventarc.googleapis.com \
        run.googleapis.com \
        pubsub.googleapis.com \
        bigquery.googleapis.com \
        secretmanager.googleapis.com \
        --project=${PROJECT_ID}

# Step 1: Ensure Pub/Sub topics exist
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:${_SDK_TAG}'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # If 'describe' fails, then run 'create'
      gcloud pubsub topics describe run-daily-ingestion || gcloud pubsub topics create run-daily-ingestion
      gcloud pubsub topics describe daily-bars-raw || gcloud pubsub topics create daily-bars-raw

# Step 2: Ensure BigQuery resources exist
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:${_SDK_TAG}'
  entrypoint: 'bash'
  args:
    - '-c'
    - | 
      # Check/Create Dataset
      bq show quant_data || bq mk -d quant_data
      
      # Check/Create Table
      # CORRECTED: Use the proper path and filename for the schema.
      bq show quant_data.daily_bars_raw || bq mk -t quant_data.daily_bars_raw ./schemas/daily_bars_schema.json

# Step 3: Ensure Pub/Sub subscription exists
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:${_SDK_TAG}'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Check/Create Subscription
      gcloud pubsub subscriptions describe ${_BIGQUERY_SUB_ID} || \
      gcloud pubsub subscriptions create ${_BIGQUERY_SUB_ID} \
        --topic=${_PUB_SUB_TOPIC} \
        --bigquery-table=${PROJECT_ID}:${_BIGQUERY_DATASET}.${_BIGQUERY_TABLE}

# STEP 4: Grant temporary permissions for the build service account
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:${_SDK_TAG}'
  id: 'GRANT_ACT_AS'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Granting 'iam.serviceAccountUser' role to Cloud Build service account..."
      gcloud iam service-accounts add-iam-policy-binding ${_FUNCTION_SERVICE_ACCOUNT} \
        --member="serviceAccount:${_BUILD_SERVICE_ACCOUNT}" \
        --role="roles/iam.serviceAccountUser"

# STEP 5: Deploy the Gen2 Cloud Function
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:${_SDK_TAG}'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # FIX: Construct the build service account email directly using the project number substitution.
      echo "Attempting deployment using Build Service Account: ${_BUILD_SERVICE_ACCOUNT}"
      
      gcloud functions deploy ingest-daily-data \
        --gen2 \
        --region=${_GCP_REGION} \
        --runtime=python311 \
        --source=./data_ingestion \
        --trigger-topic=${_TRIGGER_TOPIC} \
        --entry-point=ingest_daily_data \
        --service-account=${_FUNCTION_SERVICE_ACCOUNT} \
        --build-service-account=${_BUILD_SERVICE_ACCOUNT} \
        --set-env-vars="GCP_PROJECT_ID=${PROJECT_ID},PUB_SUB_TOPIC=${_PUB_SUB_TOPIC},ALPACA_SECRET_NAME=projects/${_GCP_PROJECT_NUMBER}/secrets/alpaca-api-keys/versions/latest" \
        --verbosity=info

# STEP 6: Revoke the temporary permissions
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:${_SDK_TAG}'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Revoking 'iam.serviceAccountUser' role..."
      gcloud iam service-accounts remove-iam-policy-binding ${_FUNCTION_SERVICE_ACCOUNT} \
        --member="serviceAccount:${_BUILD_SERVICE_ACCOUNT}" \
        --role="roles/iam.serviceAccountUser"
  # This step runs even if a previous step fails.
  allow_failure: true
  wait_for: ['-']

# --- Build Options ---
options:
  logging: CLOUD_LOGGING_ONLY
