services:
  - type: web
    name: smallcap-quant
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: APCA_API_KEY_ID
        sync: false
      - key: APCA_API_SECRET_KEY
        sync: false
      - key: APCA_API_BASE_URL
        value: https://paper-api.alpaca.markets
      - key: ALPACA_DATA_FEED
        value: sip
      - key: POLYGON_API_KEY
        sync: false
      - key: TIINGO_API_KEY
        sync: false

cronJobs:
  - name: ingest-recent
    schedule: "45 21 * * 1-5"   # Run after US close
    command: "python -m data.ingest --days 7"
  - name: refresh-universe
    schedule: "0 14 * * 1"
    command: "python -m data.universe"
  - name: eod-pipeline
    schedule: "30 22 * * 1-5"   # After ingestion
    command: "python run_pipeline.py"
