# render.yaml
# This file defines the services for deploying the data ingestion job on Render.

services:
  # Web service to run the Flask app and handle ingestion triggers.
  - type: web
    name: bcq-web
    env: python
    plan: starter # Or your preferred instance type
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn data_ingestion.main:app"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: ALPACA_API_KEY
        fromSecret: true
      - key: ALPACA_SECRET_KEY
        fromSecret: true
      - key: DATABASE_URL
        fromDatabase:
          name: bcq-db
          property: connectionString

  # Cron job to trigger the web service's /ingest endpoint.
  - type: cron
    name: bcq-cron-daily
    region: oregon
    schedule: "0 13 * * MON-FRI" # 8:00am US/Eastern (13:00 UTC) weekdays
    # This command calls the /ingest endpoint on your already-running web service.
    # The URL is automatically available via the RENDER_EXTERNAL_URL env var.
    command: "curl -X POST $RENDER_EXTERNAL_URL/ingest"

databases:
  - name: bcq-db
    plan: starter
    region: oregon




