services:
  - type: web
    name: bcq-web
    env: python
    plan: starter
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT data_ingestion.main:app
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: ENV
        value: production
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_SECRET_KEY
        sync: false
      - key: ALPACA_BASE_URL
        value: "https://api.alpaca.markets"
      - key: DATABASE_URL
        fromDatabase:
          name: bcq-db
          property: connectionString

  - type: worker
    name: bcq-worker
    env: python
    plan: starter
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      python -m data_ingestion.run_daily
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: ENV
        value: production
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_SECRET_KEY
        sync: false
      - key: ALPACA_BASE_URL
        value: "https://api.alpaca.markets"
      - key: DATABASE_URL
        fromDatabase:
          name: bcq-db
          property: connectionString

  - type: cron
    name: bcq-cron-daily
    env: python
    plan: starter
    region: oregon
    # 13:00 UTC ~= 8:00am US/Eastern / 7:00am US/Central on Standard Time (adjust if needed)
    schedule: "0 13 * * MON-FRI"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      python -m data_ingestion.run_daily
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: ENV
        value: production
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_SECRET_KEY
        sync: false
      - key: ALPACA_BASE_URL
        value: "https://api.alpaca.markets"
      - key: DATABASE_URL
        fromDatabase:
          name: bcq-db
          property: connectionString

databases:
  - name: bcq-db
    plan: basic-4gb        # cost-conscious, current valid tier
    region: oregon
    postgresMajorVersion: "16"
    diskSizeGB: 30         # adjust anytime; increase as data grows


