services:
  - type: web
    name: smallcap-quant
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: POLYGON_API_KEY
        sync: false
      - key: APCA_API_KEY_ID
        sync: false
      - key: APCA_API_SECRET_KEY
        sync: false
      - key: APCA_API_BASE_URL
        value: https://paper-api.alpaca.markets
      - key: ALPACA_DATA_FEED
        value: sip
      - key: PIPELINE_SYNC_BROKER
        value: "false"

cronJobs:
  - name: ingest-recent
    # 21:45 UTC ≈ 4:45pm ET (after US close)
    schedule: "45 21 * * 1-5"
    command: "python -m data.ingest --days 7"
  - name: refresh-universe
    # Mondays 14:00 UTC
    schedule: "0 14 * * 1"
    command: "python -m data.universe"
  - name: eod-pipeline
    # After ingestion: 22:30 UTC
    schedule: "30 22 * * 1-5"
    command: "python run_pipeline.py --days 7"
