services:
  # Web service (Flask + gunicorn)
  - type: web
    name: bcq-web
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    # Removed redundant dockerCommand; the Dockerfile CMD is used automatically.
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: ENV
        value: production
      - key: ALPACA_BASE_URL
        value: "https://api.alpaca.markets"
      - key: ALPACA_FEED
        value: "sip"
      # Default days for the /ingest endpoint if 'days' parameter is not provided
      - key: BACKFILL_DAYS
        value: "5"
      - key: DATABASE_URL
        fromDatabase:
          name: bcq-db
          property: connectionString
      # Note: Secrets (ALPACA/TIINGO keys) are now managed by the Env Group

  # Cron job to run ingestion on a schedule
  - type: cron
    name: bcq-cron-daily
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    schedule: "0 13 * * MON-FRI"
    dockerCommand: |
      python -m data_ingestion.run_daily
    envVars:
      - key: ENV
        value: production
      - key: ALPACA_BASE_URL
        value: "https://api.alpaca.markets"
      - key: ALPACA_FEED
        value: "sip"
      # Cron jobs should backfill only a couple of days to stay fresh
      - key: BACKFILL_DAYS
        value: "2"
      - key: DATABASE_URL
        fromDatabase:
          name: bcq-db
          property: connectionString

databases:
  - name: bcq-db
    plan: basic-4gb
    region: oregon
    postgresMajorVersion: "16"
    diskSizeGB: 30
