services:
  # Web service (Flask + gunicorn)
  - type: web
    name: bcq-web
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: ENV
        value: production
      - key: ALPACA_BASE_URL
        value: "https://api.alpaca.markets"
      - key: ALPACA_FEED
        value: "sip"
      - key: BACKFILL_DAYS
        value: "5"
      - key: TIINGO_API_KEY
        value: "" # Set via Render dashboard
      - key: DATABASE_URL
        fromDatabase:
          name: bcq-db
          property: connectionString

  # Worker service used for manual backfills or on‑demand ingestion
  - type: worker
    name: bcq-worker
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    dockerCommand: |
      python -m data_ingestion.run_daily
    autoDeploy: true
    envVars:
      - key: ENV
        value: production
      - key: ALPACA_BASE_URL
        value: "https://api.alpaca.markets"
      - key: ALPACA_FEED
        value: "sip"
      # Adjust for large one‑off jobs
      - key: BACKFILL_DAYS
        value: "3650"
      - key: TIINGO_API_KEY
        value: ""
      - key: DATABASE_URL
        fromDatabase:
          name: bcq-db
          property: connectionString

  # Cron job to run ingestion on a schedule
  - type: cron
    name: bcq-cron-daily
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    # Weekdays at 13:00 UTC
    schedule: "0 13 * * MON-FRI"
    dockerCommand: |
      python -m data_ingestion.run_daily
    envVars:
      - key: ENV
        value: production
      - key: ALPACA_BASE_URL
        value: "https://api.alpaca.markets"
      - key: ALPACA_FEED
        value: "sip"
      # Cron jobs should backfill only a couple of days
      - key: BACKFILL_DAYS
        value: "2"
      - key: TIINGO_API_KEY
        value: ""
      - key: DATABASE_URL
        fromDatabase:
          name: bcq-db
          property: connectionString

databases:
  - name: bcq-db
    plan: basic-4gb
    region: oregon
    postgresMajorVersion: "16"
    diskSizeGB: 30
