services:
  # Web service (Flask + gunicorn)
  - type: web
    name: bcq-web
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    # Optional: you can omit this to use Dockerfile's CMD
    dockerCommand: >
      gunicorn -k gthread -w ${WEB_CONCURRENCY:-2} --threads ${THREADS:-4}
      --timeout ${TIMEOUT:-120} --keep-alive ${KEEP_ALIVE:-5}
      --max-requests ${MAX_REQUESTS:-1000} --max-requests-jitter ${MAX_REQUESTS_JITTER:-100}
      --access-logfile - --error-logfile -
      -b 0.0.0.0:${PORT:-8080} data_ingestion.main:app
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: ENV
        value: production
      - key: ALPACA_BASE_URL
        value: "https://api.alpaca.markets"
      # Free accounts generally need "iex"; set "sip" only if your plan supports it
      - key: ALPACA_FEED
        value: "iex"
      - key: BACKFILL_DAYS
        value: "5"
      - key: TIINGO_API_KEY
        value: ""
      - key: DATABASE_URL
        fromDatabase:
          name: bcq-db
          property: connectionString

  # Worker service used for manual backfills or on‑demand ingestion
  - type: worker
    name: bcq-worker
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    dockerCommand: >
      python -m data_ingestion.run_daily
    autoDeploy: true
    envVars:
      - key: ENV
        value: production
      - key: ALPACA_BASE_URL
        value: "https://api.alpaca.markets"
      - key: ALPACA_FEED
        value: "iex"
      - key: BACKFILL_DAYS
        value: "3650"
      - key: TIINGO_API_KEY
        value: ""
      - key: DATABASE_URL
        fromDatabase:
          name: bcq-db
          property: connectionString

  # Cron job to run ingestion on a schedule (weekdays at 13:00 UTC ≈ 8 AM US/Central)
  - type: cron
    name: bcq-cron-daily
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    schedule: "0 13 * * MON-FRI"
    dockerCommand: >
      python -m data_ingestion.run_daily
    envVars:
      - key: ENV
        value: production
      - key: ALPACA_BASE_URL
        value: "https://api.alpaca.markets"
      - key: ALPACA_FEED
        value: "iex"
      - key: BACKFILL_DAYS
        value: "2"
      - key: TIINGO_API_KEY
        value: ""
      - key: DATABASE_URL
        fromDatabase:
          name: bcq-db
          property: connectionString

databases:
  - name: bcq-db
    plan: basic-4gb
    region: oregon
    postgresMajorVersion: "16"
    diskSizeGB: 30

