services:
  - type: web
    name: smallcap-quant
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: APCA_API_KEY_ID
        sync: false
      - key: APCA_API_SECRET_KEY
        sync: false
      - key: APCA_API_BASE_URL
        value: https://api.alpaca.markets
      - key: ALPACA_DATA_FEED
        value: sip
      - key: TIINGO_API_KEY
        sync: false

cronJobs:
  - name: ingest-recent
    schedule: "30 21 * * 1-5"   # Weekdays 21:30 UTC (post-close ingestion)
    command: "python -m data.ingest --days 7"
  - name: refresh-universe
    schedule: "0 14 * * 1"      # Mondays 14:00 UTC
    command: "python -m data.universe"
