"""add_task_status_table

Revision ID: 20250827_add_task_status_table
Revises: alembic_versions_20250827_08_add_feature_extensions
Create Date: 2025-01-27 16:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '20250827_add_task_status_table'
down_revision = 'alembic_versions_20250827_08_add_feature_extensions'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_status',
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index('ix_task_status_created_at', 'task_status', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_status_created_at', table_name='task_status')
    op.drop_table('task_status')
    # ### end Alembic commands ###